app:
  server:
    name: GlassFish
    detail: this is GlassFish for production environment.

spring:
  datasource:
    url: jdbc:oracle:thin:@hostname:80:prodenv
    username: oracle-prod
    password: prod-en

