server:
  port: 8083

app:
  server:
    name: profiles
    detail: this is general server

spring:
  profiles:
    active:
      - dev
  datasource:
    url: jdbc:hsqldb:hsql://localhost/profiles
    username: profiles-user
    password: 12345
  application:
    name: This is a demo application for understanding profiles in microservices
